AWSTemplateFormatVersion: '2010-09-09'
Description: MISCONFIGURATION - IAM user with ec2 full access

Metadata:
  Misconfiguration:
    Category: IAM-OverPermission
    Severity: HIGH
    RuleId: IAM-006
    Description: IAM user has ec2:* permission

Resources:
  EC2FullAccessUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "ec2-user-${AWS::StackName}"
      Tags:
        - Key: Name
          Value: EC2FullAccessUser

  EC2FullAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "EC2Policy-${AWS::StackName}"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "ec2:*"
            Resource: "*"
      Users:
        - !Ref EC2FullAccessUser

  UserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref EC2FullAccessUser

Outputs:
  Username:
    Value: !Ref EC2FullAccessUser
